### ISSUE TITLE
FATAL: database "/taigadocker_taigaback_1/postgres" does not exist

### ISSUE THREAD

**Issue by justintime4tea** [htdvisser/taiga-docker#10]
I noticed really recent changes that may have broken the provisioning pipeline?

I had the docker-compose htdvisser/taiga group of containers working flawlessly yesterday somewhere around 12:00pm PST but after coming home attempted to pull/run again I got failing results. Image wouldn't finish pulling and/or extracting and would simply hang.

I do see you are actively working on this now so I'm sure if it's not isolated to my system and is a real issue you'll hash this out soon enough. Thought I'd leave a snippet of the failure in my logs in-case they help narrow down the issue at all or perhaps I've made a common mistake and you've encountered this as well at some point :)

I am a developer as well so if you need anything tested or additional log entries/analysis let me know!
##### [.../taiga-docker.git/]:[$] docker-compose up

```
taigaback_1  | Copying '/usr/local/taiga/taiga-back/taiga/base/api/static/api/js/prettify-min.js'
taigaback_1  | Copying '/usr/local/taiga/taiga-back/taiga/base/api/static/api/js/jquery-1.8.1-min.js'
taigaback_1  | Copying '/usr/local/taiga/taiga-back/taiga/users/static/img/user-noimage.png'
taigaback_1  | 
taigaback_1  | 950 static files copied to '/usr/local/taiga/static'.
taigaback_1  | Waiting for Postgresql to be available...
db_1         |  done
db_1         | server started
db_1         | CREATE DATABASE
db_1         | 
db_1         | CREATE ROLE
db_1         | 
db_1         | 
db_1         | /docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1         | 
db_1         | LOG:  received fast shutdown request
db_1         | LOG:  aborting any active transactions
db_1         | LOG:  autovacuum launcher shutting down
db_1         | LOG:  shutting down
db_1         | waiting for server to shut down....LOG:  database system is shut down
db_1         |  done
db_1         | server stopped
db_1         | 
db_1         | PostgreSQL init process complete; ready for start up.
db_1         | 
db_1         | LOG:  database system was shut down at 2015-09-30 14:05:23 UTC
db_1         | LOG:  MultiXact member wraparound protections are now enabled
db_1         | LOG:  database system is ready to accept connections
db_1         | LOG:  autovacuum launcher started
db_1         | LOG:  incomplete startup packet
db_1         | FATAL:  database "/taigadocker_taigaback_1/postgres" does not exist
taigaback_1  | Trying import local.py settings...
taigaback_1  | Traceback (most recent call last):
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/db/backends/__init__.py", line 133, in ensure_connection
taigaback_1  |     self.connect()
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/transaction_hooks/mixin.py", line 75, in connect
taigaback_1  |     super(TransactionHooksDatabaseWrapperMixin, self).connect(*a, **kw)
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/db/backends/__init__.py", line 122, in connect
taigaback_1  |     self.connection = self.get_new_connection(conn_params)
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 130, in get_new_connection
taigaback_1  |     connection = Database.connect(**conn_params)
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/psycopg2/__init__.py", line 164, in connect
taigaback_1  |     conn = _connect(dsn, connection_factory=connection_factory, async=async)
taigaback_1  | psycopg2.OperationalError: FATAL:  database "/taigadocker_taigaback_1/postgres" does not exist
taigaback_1  | 
taigaback_1  | 
taigaback_1  | The above exception was the direct cause of the following exception:
taigaback_1  | 
taigaback_1  | Traceback (most recent call last):
taigaback_1  |   File "manage.py", line 10, in <module>
taigaback_1  |     execute_from_command_line(sys.argv)
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
taigaback_1  |     utility.execute()
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
taigaback_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
taigaback_1  |     self.execute(*args, **options.__dict__)
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
taigaback_1  |     output = self.handle(*args, **options)
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 63, in handle
taigaback_1  |     executor = MigrationExecutor(connection, self.migration_progress_callback)
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/db/migrations/executor.py", line 17, in __init__
taigaback_1  |     self.loader = MigrationLoader(self.connection)
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/db/migrations/loader.py", line 48, in __init__
taigaback_1  |     self.build_graph()
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/db/migrations/loader.py", line 183, in build_graph
taigaback_1  |     self.applied_migrations = recorder.applied_migrations()
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/db/migrations/recorder.py", line 59, in applied_migrations
taigaback_1  |     self.ensure_schema()
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/db/migrations/recorder.py", line 49, in ensure_schema
taigaback_1  |     if self.Migration._meta.db_table in self.connection.introspection.get_table_list(self.connection.cursor()):
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/db/backends/__init__.py", line 167, in cursor
taigaback_1  |     cursor = utils.CursorWrapper(self._cursor(), self)
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/db/backends/__init__.py", line 138, in _cursor
taigaback_1  |     self.ensure_connection()
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/db/backends/__init__.py", line 133, in ensure_connection
taigaback_1  |     self.connect()
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/db/utils.py", line 94, in __exit__
taigaback_1  |     six.reraise(dj_exc_type, dj_exc_value, traceback)
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
taigaback_1  |     raise value.with_traceback(tb)
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/db/backends/__init__.py", line 133, in ensure_connection
taigaback_1  |     self.connect()
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/transaction_hooks/mixin.py", line 75, in connect
taigaback_1  |     super(TransactionHooksDatabaseWrapperMixin, self).connect(*a, **kw)
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/db/backends/__init__.py", line 122, in connect
taigaback_1  |     self.connection = self.get_new_connection(conn_params)
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 130, in get_new_connection
taigaback_1  |     connection = Database.connect(**conn_params)
taigaback_1  |   File "/usr/local/lib/python3.4/site-packages/psycopg2/__init__.py", line 164, in connect
taigaback_1  |     conn = _connect(dsn, connection_factory=connection_factory, async=async)
taigaback_1  | django.db.utils.OperationalError: FATAL:  database "/taigadocker_taigaback_1/postgres" does not exist
taigaback_1  | 
taigaback_1  | 2015-09-30 14:05:26 circus[21] [INFO] Starting master on pid 21
taigaback_1  | 2015-09-30 14:05:26 circus[21] [INFO] Arbiter now waiting for commands
taigaback_1  | 2015-09-30 14:05:26 circus[21] [INFO] taiga started
taigaback_1  | 2015-09-30 14:05:26 circus[21] [INFO] circusd-stats started
taigaback_1  | 2015-09-30 14:05:26 circus[26] [INFO] Starting the stats streamer
```

**Comment by justintime4tea** [comment]
This may in-fact be an issue on my end because I must use docker-compose.yml for docker-compose to work and hadn't re-copied the modified taiga.yml. Will close if this is the case.

**Comment by beevelop** [comment]
I can reproduce this behaviour. The bug is caused by the recent changes of 4a13166897391f38ab2d1713bec4662138469d8d.
There is a conflict with the `POSTGRES_NAME` environment variable. You can simply circumvent this bug by explicitly defining `POSTGRES_NAME: taiga` in your `docker-compose.yml`. Nonetheless I suggest to change the naming of the configuration variable to something more general like `DB_NAME`.

**Comment by htdvisser** [comment]
Renamed `POSTGRES_NAME` to `POSTGRES_DB_NAME`. My apologies for merging PR#9 without fully testing it.
