### ISSUE TITLE
Is valid  taiga.yml for 3.0.0 taiga upgrade?

### ISSUE THREAD

**Issue by jujes** [htdvisser/taiga-docker#25]
Hi, someone know if possible install the new version of taiga 3.0.0 whit the taiga.yml of this repo?
https://blog.taiga.io/taiga-stellaria-borealis-release-300.html

Regards,

**Comment by codablock** [comment]
If noone else is already working on Taiga 3.0.0 support, I can start working on that. I'm currently deploying 3.0.0 in Docker and would prefer to have a reproducible and reusable solution.

**Comment by lenybernard** [comment]
Hello @codablock, that would be really cool, thank you.

**Comment by codablock** [comment]
It turned out that it actually already works. The problems I had were related to wrong configuration. Did anyone of you have problems?

**Comment by htdvisser** [comment]
Cool, @codablock! I'm not working on this project anymore, but if you're interested in keeping this repo up-to-date, I can add you as a collaborator! Let me know!

**Comment by rawlingsj** [comment]
@codablock what was the config you needed to change?  

I've just tried the taiga.yml but when I try to log in with the admin/123123 credentials I get

```
Failed to load resource: the server responded with a status of 400 (Bad Request) http://localhost/api/v1/auth
```

in the browser console, was that the same issue you ran into?

**Comment by codablock** [comment]
@rawlingsj What do the docker/docker-compose logs say?

**Comment by rawlingsj** [comment]
@codablock are you just after the logs from when I try to login?  If so:

```
taigaback_1   |   Applying wiki.0004_auto_20160928_0540...Trying import local.py settings...
taigaback_1   |  OK
taigaback_1   | 2016-10-24 15:09:56 circus[21] [INFO] Starting master on pid 21
taigaback_1   | 2016-10-24 15:09:56 circus[21] [INFO] Arbiter now waiting for commands
taigaback_1   | 2016-10-24 15:09:56 circus[21] [INFO] taiga started
taigaback_1   | 2016-10-24 15:09:56 circus[21] [INFO] circusd-stats started
taigaback_1   | 2016-10-24 15:09:56 circus[26] [INFO] Starting the stats streamer
taigafront_1  | 172.17.0.1 - - [24/Oct/2016:15:13:24 +0000] "GET / HTTP/1.1" 200 26739 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" "-"
taigafront_1  | 172.17.0.1 - - [24/Oct/2016:15:13:24 +0000] "GET /conf.json HTTP/1.1" 200 262 "http://localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" "-"
taigafront_1  | 172.17.0.1 - - [24/Oct/2016:15:13:25 +0000] "GET /v-1476536352617/locales/taiga/locale-en.json HTTP/1.1" 200 19681 "http://localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" "-"
taigafront_1  | 172.17.0.1 - - [24/Oct/2016:15:13:25 +0000] "GET /api/v1/projects?discover_mode=true&order_by=-total_activity_last_week HTTP/1.1" 200 33 "http://localhost/discover" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" "-"
taigafront_1  | 172.17.0.1 - - [24/Oct/2016:15:13:25 +0000] "GET /api/v1/projects?discover_mode=true&order_by=-total_fans_last_week HTTP/1.1" 200 33 "http://localhost/discover" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" "-"
taigafront_1  | 172.17.0.1 - - [24/Oct/2016:15:13:25 +0000] "GET /api/v1/projects?discover_mode=true&is_featured=true HTTP/1.1" 200 33 "http://localhost/discover" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" "-"
taigafront_1  | 172.17.0.1 - - [24/Oct/2016:15:13:25 +0000] "GET /api/v1/stats/discover HTTP/1.1" 200 55 "http://localhost/discover" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" "-"
taigafront_1  | 172.17.0.1 - - [24/Oct/2016:15:13:34 +0000] "POST /api/v1/auth HTTP/1.1" 400 131 "http://localhost/login?next=%252Fdiscover" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" "-"
taigafront_1  | 172.17.0.1 - - [24/Oct/2016:15:13:59 +0000] "GET /v-1476536352617/js/maps/app.js.map HTTP/1.1" 200 2135004 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" "-"
taigafront_1  | 172.17.0.1 - - [24/Oct/2016:15:13:59 +0000] "GET /v-1476536352617/js/maps/libs.js.map HTTP/1.1" 200 4781799 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" "-"
taigafront_1  | 172.17.0.1 - - [24/Oct/2016:15:18:47 +0000] "GET /api/v1/auth HTTP/1.1" 405 115 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" "-"
taigafront_1  | 2016/10/24 15:18:47 [error] 12#0: *14 open() "/usr/local/taiga/taiga-front-dist/dist/favicon.ico" failed (2: No such file or directory), client: 172.17.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/api/v1/auth"
```

**Comment by codablock** [comment]
@rawlingsj Did you follow the instructions on https://github.com/htdvisser/taiga-docker/tree/stable/taiga-back?
My first guess would be that you did not do the "Database Initialization" part. If you did that, then I don't know what the cause could be.

The configuration problems I had were related to additions (PUBLIC_REGISTER_ENABLED) made to the compose file. Fixing/Reverting these changes fixed my issues. I would assume that this is not related to your problems.

**Comment by rawlingsj** [comment]
my bad,  I totally missed that - thanks @codablock all sorted!

**Comment by codablock** [comment]
@rawlingsj so is everything working? if yes, I think this one can be closed?

**Comment by rawlingsj** [comment]
@codablock I was able to log in using the default admin username yes many thanks.  I did have an issue signing up a new user but perhaps this is something unrelated.  Should this work?  

```
taigafront_1  | 172.17.0.1 - - [25/Oct/2016:08:36:30 +0000] "POST /api/v1/auth/register HTTP/1.1" 500 48 "http://localhost/register?next=%252Fdiscover" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" "-"
```

I'll double check the docs and config, I'm not setting the hostname in the dockercompose yaml but FWIW I've actually been creating a kubernetes yaml instead as thats our target platform.  I also get signup errors with that too.

**Comment by codablock** [comment]
@rawlingsj You should check the backend logs as well in this case. If it does not show anything, try to figure out if there is anything to enable verbose debug messages on the backend.

**Comment by rawlingsj** [comment]
there's no information in the backend logs apart from the last message after the pod is initially started.

```
Trying import local.py settings...

0 static files copied to '/usr/local/taiga/static', 934 unmodified.
Waiting for Postgresql to be available...
Trying import local.py settings...
Operations to perform:
  Apply all migrations: custom_attributes, issues, history, userstorage, userstories, feedback, notifications, contenttypes, github, gogs, tasks, projects, epics, likes, easy_thumbnails, timeline, webhooks, sessions, wiki, gitlab, djmail, milestones, external_apps, attachments, references, auth, admin, users, votes, bitbucket
Running migrations:
  No migrations to apply.
2016-10-25 08:21:54 circus[20] [INFO] Starting master on pid 20
2016-10-25 08:21:54 circus[20] [INFO] Arbiter now waiting for commands
2016-10-25 08:21:54 circus[20] [INFO] taiga started
2016-10-25 08:21:54 circus[20] [INFO] circusd-stats started
2016-10-25 08:21:54 circus[25] [INFO] Starting the stats streamer
```

I'll have a crack at increasing log levels, it's probably right that I create a different issue which is a more specific as I was able to log into taiga + create projects which is the scope of this issue.

Thanks for the suggestions @codablock, dont keep the issue open based on my current issues.

**Comment by jujes** [comment]
Hi, I back with an Database Initialization Error..
someone have the same issue?
I put here the output, hope any can tell me how fix it...
Regards,

ps. I think the issue is related with Postgresql. this is my log for taiga back...

```
Copying '/usr/local/taiga/taiga-back/taiga/base/static/emails/top-bg-update.png'
Copying '/usr/local/taiga/taiga-back/taiga/users/static/img/user-noimage.png'

934 static files copied to '/usr/local/taiga/static'.
Waiting for Postgresql to be available...
tcp://172.17.0.3:5432: forward host lookup failed: Unknown host
tcp://172.17.0.3:5432: forward host lookup failed: Unknown host
tcp://172.17.0.3:5432: forward host lookup failed: Unknown host
```


```
root@taiga:/usr/local/taiga/taiga-back# python manage.py loaddata initial_user
Trying import local.py settings...
Raven is not configured (logging is disabled). Please see the documentation for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.4/site-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.4/site-packages/django/db/backends/postgresql/base.py", line 175, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.4/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: invalid port number: "tcp://172.17.0.3:5432"


The above exception was the direct cause of the following exception:


Traceback (most recent call last):
File "manage.py", line 29, in <module>
  execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
  utility.execute()
File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
  self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
  self.execute(*args, **cmd_options)
File "/usr/local/lib/python3.4/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
  return original_func(self, *args, **kwargs)
File "/usr/local/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
  output = self.handle(*args, **options)
File "/usr/local/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 59, in handle
  with transaction.atomic(using=self.using):
File "/usr/local/lib/python3.4/site-packages/django/db/transaction.py", line 158, in __enter__
  if not connection.get_autocommit():
File "/usr/local/lib/python3.4/site-packages/django/db/backends/base/base.py", line 365, in get_autocommit
  self.ensure_connection()
File "/usr/local/lib/python3.4/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
  self.connect()
File "/usr/local/lib/python3.4/site-packages/django/db/utils.py", line 95, in __exit__
  six.reraise(dj_exc_type, dj_exc_value, traceback)
File "/usr/local/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
  raise value.with_traceback(tb)
File "/usr/local/lib/python3.4/site-packages/django/db/backends/base/base.py", line 199, in ensure_connection
  self.connect()
File "/usr/local/lib/python3.4/site-packages/django/db/backends/base/base.py", line 171, in connect
  self.connection = self.get_new_connection(conn_params)
File "/usr/local/lib/python3.4/site-packages/django/db/backends/postgresql/base.py", line 175, in get_new_connection
  connection = Database.connect(**conn_params)
File "/usr/local/lib/python3.4/site-packages/psycopg2/__init__.py", line 164, in connect
  conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: invalid port number: "tcp://172.17.0.3:5432"
```

**Comment by beevelop** [comment]
This might be the result of a naming conflict. The database container's name can interfere with the ENVs used to configure the database (`POSTGRES_*`). What's the name of your Postgres container and how are you linking the database to the backend (command line, docker-compose,...)?

Have a look at #27; @nsymms describes it very well.
